@echo off
echo Creating virtual environment...
python -m venv venv

echo Activating virtual environment...
call venv\Scripts\activate

echo Installing required packages...
pip install django pillow

echo Making migrations...
python manage.py makemigrations

echo Applying migrations...
python manage.py migrate

echo Creating superuser...
python manage.py createsuperuser

echo Collecting static files...
python manage.py collectstatic

echo Starting development server...
python manage.py runserver