# Generated by Django 5.2 on 2025-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_description_case_status_alter_case_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
