# Generated by Django 5.2 on 2025-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_attorney',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.IntegerField(),
        ),
    ]
