# Generated by Django 5.1.5 on 2025-04-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='attorney',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client'),
        ),
    ]
